services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-fhir
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER:?Debes definir el usuario en el .env}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD:?Debes definir la contraseña en el .env}"
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME:-fhir_db}"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: